# Generated by Django 3.2.19 on 2024-09-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camionetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camionetas',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
